from app.logger_config import logger
from datetime import datetime


def print_batch_match_request(ml_requests, ml_donations, top_n, threshold):
    logger.info("\n" + "=" * 150)
    logger.info("RECEIVED BATCH MATCH REQUEST")
    logger.info("=" * 150)

    logger.info(f"\nBATCH REQUEST STATS:")
    logger.info(f"   • Total Requests: {len(ml_requests)}")
    logger.info(f"   • Total Donations: {len(ml_donations)}")
    logger.info(f"   • Top N: {top_n}")
    logger.info(f"   • Threshold: {threshold}")
    logger.info(f"   • Timestamp: {datetime.now().isoformat()}")

    logger.info(f"\n\n{'=' * 150}")
    logger.info(f"RECIPIENT REQUESTS ({len(ml_requests)} total)")
    logger.info(f"{'=' * 150}")

    for idx, recipient in enumerate(ml_requests, 1):
        logger.info(f"\n\n{'─' * 150}")
        logger.info(f"REQUEST #{idx}/{len(ml_requests)}")
        logger.info(f"{'─' * 150}")

        logger.info(f"\n  REQUEST IDENTIFIERS:")
        logger.info(f"     • Receive Request ID: {recipient.receiveRequestId}")
        logger.info(f"     • Recipient ID: {recipient.recipientId}")
        logger.info(f"     • User ID: {recipient.userId}")
        logger.info(f"     • Location ID: {recipient.locationId}")

        logger.info(f"\n  REQUEST DETAILS:")
        logger.info(f"     • Request Type: {recipient.requestType}")
        logger.info(f"     • Blood Type Needed: {recipient.requestedBloodType}")
        logger.info(f"     • Organ Needed: {recipient.requestedOrgan}")
        logger.info(f"     • Tissue Needed: {recipient.requestedTissue}")
        logger.info(f"     • Stem Cell Type Needed: {recipient.requestedStemCellType}")
        logger.info(f"     • Urgency Level: {recipient.urgencyLevel}")
        logger.info(f"     • Quantity: {recipient.quantity}")
        logger.info(f"     • Request Date: {recipient.requestDate}")
        logger.info(f"     • Days Waiting: {recipient.daysWaiting}")

        logger.info(f"\n  PHYSICAL INFO:")
        logger.info(f"     • Age: {recipient.age} years")
        logger.info(f"     • DOB: {recipient.dob}")
        logger.info(f"     • Weight: {recipient.weight} kg")
        logger.info(f"     • Height: {recipient.height} cm")
        logger.info(f"     • BMI: {recipient.bmi}")
        logger.info(f"     • Body Size: {recipient.bodySize}")

        logger.info(f"\n  MEDICAL INFORMATION:")
        logger.info(f"     • Hemoglobin Level: {recipient.hemoglobinLevel} g/dL")
        logger.info(f"     • Blood Glucose Level: {recipient.bloodGlucoseLevel} mg/dL")
        logger.info(f"     • Has Diabetes: {recipient.hasDiabetes}")
        logger.info(f"     • Blood Pressure: {recipient.bloodPressure}")
        logger.info(f"     • Has Infectious Diseases: {recipient.hasInfectiousDiseases}")
        logger.info(f"     • Infectious Disease Details: {recipient.infectiousDiseaseDetails}")
        logger.info(f"     • Creatinine Level: {recipient.creatinineLevel} mg/dL")
        logger.info(f"     • Liver Function Tests: {recipient.liverFunctionTests}")
        logger.info(f"     • Cardiac Status: {recipient.cardiacStatus}")
        logger.info(f"     • Pulmonary Function: {recipient.pulmonaryFunction}")
        logger.info(f"     • Overall Health Status: {recipient.overallHealthStatus}")
        logger.info(f"     • Diagnosis: {recipient.diagnosis}")
        logger.info(f"     • Allergies: {recipient.allergies}")

        logger.info(f"\n  LIFESTYLE INFO:")
        logger.info(f"     • Smoking Status: {recipient.smokingStatus}")
        logger.info(f"     • Pack Years: {recipient.packYears}")
        logger.info(f"     • Alcohol Status: {recipient.alcoholStatus}")
        logger.info(f"     • Drinks Per Week: {recipient.drinksPerWeek}")

        logger.info(f"\n  LOCATION:")
        logger.info(f"     • Latitude: {recipient.latitude}")
        logger.info(f"     • Longitude: {recipient.longitude}")
        logger.info(f"     • City: {recipient.city}")
        logger.info(f"     • District: {recipient.district}")
        logger.info(f"     • State: {recipient.state}")
        logger.info(f"     • Country: {recipient.country}")

        if any([recipient.hlaA1, recipient.hlaA2, recipient.hlaB1, recipient.hlaB2]):
            logger.info(f"\n  HLA TYPING:")
            logger.info(f"     • HLA-A: {recipient.hlaA1} / {recipient.hlaA2}")
            logger.info(f"     • HLA-B: {recipient.hlaB1} / {recipient.hlaB2}")
            logger.info(f"     • HLA-C: {recipient.hlaC1} / {recipient.hlaC2}")
            logger.info(f"     • HLA-DR: {recipient.hlaDR1} / {recipient.hlaDR2}")
            logger.info(f"     • HLA-DQ: {recipient.hlaDQ1} / {recipient.hlaDQ2}")
            logger.info(f"     • HLA-DP: {recipient.hlaDP1} / {recipient.hlaDP2}")
            logger.info(f"     • High Resolution: {recipient.hlaHighResolution}")
            logger.info(f"     • HLA String: {recipient.hlaString}")

    logger.info(f"\n\n{'=' * 150}")
    logger.info(f"AVAILABLE DONATIONS ({len(ml_donations)} total)")
    logger.info(f"{'=' * 150}")

    for idx, donation in enumerate(ml_donations, 1):
        logger.info(f"\n\n{'─' * 150}")
        logger.info(f"DONATION #{idx}/{len(ml_donations)}")
        logger.info(f"{'─' * 150}")

        logger.info(f"\n  DONATION IDENTIFIERS:")
        logger.info(f"     • Donation ID: {donation.donationId}")
        logger.info(f"     • Donor ID: {donation.donorId}")
        logger.info(f"     • User ID: {donation.userId}")
        logger.info(f"     • Location ID: {donation.locationId}")

        logger.info(f"\n  DONATION DETAILS:")
        logger.info(f"     • Donation Type: {donation.donationType}")
        logger.info(f"     • Blood Type: {donation.bloodType}")
        logger.info(f"     • Donation Date: {donation.donationDate}")
        logger.info(f"     • Quantity: {donation.quantity}")
        logger.info(f"     • Tissue Type: {donation.tissueType}")
        logger.info(f"     • Stem Cell Type: {donation.stemCellType}")

        logger.info(f"\n  DONOR PHYSICAL INFO:")
        logger.info(f"     • Age: {donation.age} years")
        logger.info(f"     • DOB: {donation.dob}")
        logger.info(f"     • Weight: {donation.weight} kg")
        logger.info(f"     • Height: {donation.height} cm")
        logger.info(f"     • BMI: {donation.bmi}")
        logger.info(f"     • Body Size: {donation.bodySize}")
        logger.info(f"     • Is Living Donor: {donation.isLivingDonor}")

        logger.info(f"\n  DONOR MEDICAL INFORMATION:")
        logger.info(f"     • Hemoglobin Level: {donation.hemoglobinLevel} g/dL")
        logger.info(f"     • Blood Glucose Level: {donation.bloodGlucoseLevel} mg/dL")
        logger.info(f"     • Has Diabetes: {donation.hasDiabetes}")
        logger.info(f"     • Blood Pressure: {donation.bloodPressure}")
        logger.info(f"     • Has Diseases: {donation.hasDiseases}")
        logger.info(f"     • Has Infectious Diseases: {donation.hasInfectiousDiseases}")
        logger.info(f"     • Infectious Disease Details: {donation.infectiousDiseaseDetails}")
        logger.info(f"     • Creatinine Level: {donation.creatinineLevel} mg/dL")
        logger.info(f"     • Liver Function Tests: {donation.liverFunctionTests}")
        logger.info(f"     • Cardiac Status: {donation.cardiacStatus}")
        logger.info(f"     • Pulmonary Function: {donation.pulmonaryFunction}")
        logger.info(f"     • Overall Health Status: {donation.overallHealthStatus}")

        logger.info(f"\n  MEDICAL CLEARANCE:")
        logger.info(f"     • Medical Clearance: {donation.medicalClearance}")
        logger.info(f"     • Recent Tattoo/Piercing: {donation.recentTattoo}")
        logger.info(f"     • Recent Vaccination: {donation.recentVaccination}")
        logger.info(f"     • Recent Surgery: {donation.recentSurgery}")
        logger.info(f"     • Chronic Diseases: {donation.chronicDiseases}")
        logger.info(f"     • Allergies: {donation.allergies}")

        logger.info(f"\n  DONATION HISTORY:")
        logger.info(f"     • Last Donation Date: {donation.lastDonationDate}")
        logger.info(f"     • Days Since Last Donation: {donation.daysSinceLastDonation}")

        logger.info(f"\n  DONOR LIFESTYLE INFO:")
        logger.info(f"     • Smoking Status: {donation.smokingStatus}")
        logger.info(f"     • Pack Years: {donation.packYears}")
        logger.info(f"     • Quit Smoking Date: {donation.quitSmokingDate}")
        logger.info(f"     • Alcohol Status: {donation.alcoholStatus}")
        logger.info(f"     • Drinks Per Week: {donation.drinksPerWeek}")
        logger.info(f"     • Quit Alcohol Date: {donation.quitAlcoholDate}")
        logger.info(f"     • Alcohol Abstinence Months: {donation.alcoholAbstinenceMonths}")

        logger.info(f"\n  DONOR LOCATION:")
        logger.info(f"     • Latitude: {donation.latitude}")
        logger.info(f"     • Longitude: {donation.longitude}")
        logger.info(f"     • City: {donation.city}")
        logger.info(f"     • District: {donation.district}")
        logger.info(f"     • State: {donation.state}")
        logger.info(f"     • Country: {donation.country}")

        if donation.donationType == 'ORGAN' or donation.organType:
            logger.info(f"\n  ORGAN DETAILS:")
            logger.info(f"     • Organ Type: {donation.organType}")
            logger.info(f"     • Organ Quality: {donation.organQuality}")
            logger.info(f"     • Organ Viability Expiry: {donation.organViabilityExpiry}")
            logger.info(f"     • Organ Viability Hours: {donation.organViabilityHours} hours")
            logger.info(f"     • Cold Ischemia Time: {donation.coldIschemiaTime} minutes")
            logger.info(f"     • Organ Perfused: {donation.organPerfused}")
            logger.info(f"     • Organ Weight: {donation.organWeight} kg")
            logger.info(f"     • Organ Size: {donation.organSize}")
            logger.info(f"     • Has Abnormalities: {donation.hasAbnormalities}")

        if any([donation.hlaA1, donation.hlaA2, donation.hlaB1, donation.hlaB2]):
            logger.info(f"\n  DONOR HLA TYPING:")
            logger.info(f"     • HLA-A: {donation.hlaA1} / {donation.hlaA2}")
            logger.info(f"     • HLA-B: {donation.hlaB1} / {donation.hlaB2}")
            logger.info(f"     • HLA-C: {donation.hlaC1} / {donation.hlaC2}")
            logger.info(f"     • HLA-DR: {donation.hlaDR1} / {donation.hlaDR2}")
            logger.info(f"     • HLA-DQ: {donation.hlaDQ1} / {donation.hlaDQ2}")
            logger.info(f"     • HLA-DP: {donation.hlaDP1} / {donation.hlaDP2}")
            logger.info(f"     • High Resolution: {donation.hlaHighResolution}")
            logger.info(f"     • HLA String: {donation.hlaString}")

    logger.info(f"\n\n{'=' * 150}")
    logger.info(f"DATA VALIDATION COMPLETE")
    logger.info(f"{'=' * 150}")
    logger.info(f"\nSUMMARY:")
    logger.info(f"   • Total Requests Received: {len(ml_requests)}")
    logger.info(f"   • Total Donations Received: {len(ml_donations)}")
    logger.info(f"   • Processing Timestamp: {datetime.now().isoformat()}")
    logger.info(f"\n{'=' * 150}\n")
