spring.config.import=optional:file:.env[.properties],optional:file:./service-registry/.env[.properties],optional:file:./microservices/service-registry/.env[.properties]
spring.application.name=service-registry
server.port=${SERVER_PORT:8761}

eureka.instance.hostname=${EUREKA_HOSTNAME:eureka-server}
eureka.client.fetch-registry=false
eureka.client.register-with-eureka=false
